#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

agent.add_public_service(os.environ['MODULE_ID'], [
    "21115/tcp",
    "21116/tcp",
    "21116/udp",
    "21117/tcp",
    "21118/tcp",
    "21119/tcp",
])

# Ignore exit code
